---
title: "01_BusinessUnderstanding"
output: pdf_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```

# Business Understanding

Businesses are making effort to achieve an edge with their content marketing program. Showing an article’s reading time to each article can have a profound and positive effect on reader engagement levels. The first benefit is that users to help them choose the right article for the right amount of available time they have. Another advantage is that estimated reading time impacts engagement metrics seriously. Lastly, it helps to make analyzes according to certain groups.

Reading time is calculated based on the average number of words a person reads per minute. Generally, this average value per minute is between 200 and 250 words. Therefore, the total number of words in the article is divided by this determined average.

However, scientific articles are not like blog posts. Reading time varies according to one's knowledge, age, country even article subject. For example, professionals can read articles more quickly than students or older people who read slower. Hence,  we are not making an accurate estimate by using the conventional calculation method.

In this study, the data will be analyzed and the article reading time will be examined in which groups and how it changes. Then, a regression model using these features will be developed that can predict article reading time on a per-person basis.


##  Business objectives

The following sections will focus on:

- 1. Does the time spent on these articles differ according to certain groups ?
- 2. How effective are the articles in the course ? 
- 3. What is the average read time for each article ?
- 4. Can we estimate the reading time per person ?

##  Data Mining Goals

The business objectives are defined, it's time to translate it into a data mining reality

- Explore and find features one of the run data sets 
- Build predictive model with 2 min RMSE
