name: Deploy to Firebase

on:
  push:
    branches: [ master ]
    paths-ignore:
      - '.github/workflows/**' # Changes in workflow files will not trigger this action

jobs:
  render_and_deploy:
    # The type of runner that the job will run on
    runs-on: macOS-latest
    steps:
    - uses: actions/checkout@v2
    - uses: r-lib/actions/setup-r@v1
    - uses: r-lib/actions/setup-pandoc@v1
    - name: install required packages
      run: Rscript -e 'install.packages(c("rmarkdown","gratia","ProjectTemplate"))'
    - name: render Rmd  
      run: Rscript -e 'rmarkdown::render("reports/report.Rmd", output_format = "html_document", output_file="index.html", output_dir="public")'
    - name: commit rendered file
      run: |
        git add public/index.html
        git commit -m "Re-build Rmd File by github action" || echo "No changes to commit"
        git push origin master || echo "No changes to commit"
    - uses: FirebaseExtended/action-hosting-deploy@v0
      with:
        repoToken: '${{ secrets.GITHUB_TOKEN }}'
        firebaseServiceAccount: '${{ secrets.FIREBASE_SERVICE_ACCOUNT_DATAMANAGEMENT_4BE96 }}'
        channelId: live
        projectId: datamanagement-4be96
